#!/usr/bin/env bash
# Prints the correct answers for the OSI model questions

echo -n "The OSI model is a conceptual model that characterizes the "
echo -n "communication functions of a telecommunication system "
echo "without regard to their underlying internal structure and technology"
echo "From the lowest to the highest level"
