#!/usr/bin/env bash
# Configures the server to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sed 's/127.0.0.1/127.0.0.2/g' /etc/hosts > hosts.tmp
cat hosts.tmp > /etc/hosts
rm hosts.tmp
echo "8.8.8.8 facebook.com" >> /etc/hosts
